[package]
name = "QRScanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.28.1"
rdev = "0.5.3"
screenshots = "0.8.10"
