[package]
name = "QRScanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.28.1"
image = "0.25.2"
rdev = "0.5.3"
rqrr = "0.7.1"
screenshots = "0.8.10"
webbrowser = "1.0.1"
